Feature/linevych car
20210502-FE/Linevych_car pull request #1
Opened 2021-06-27 12:21 UTC by Roman240594

2021-07-04 14:48 UTC, JuliaSavych requested changes

2021-07-04 14:48 UTC, jules-js commented on app/index.html
> +                    <div class="banner__content-img position_relative">
banner image as background

2021-07-04 14:48 UTC, jules-js commented on app/index.html
> +                <a href="#"><img class="logo header__logo" src="assets/images/LOGOAuto.png" alt="logo"></a>
href="/"

2021-07-04 14:48 UTC, jules-js commented on app/index.html
> +                    <div class="work__item text-center flex_basis-25">
flex_basis-25 - no such class in browser
flex_basis-25 is a midificator of .flex block
you can't use modificators without element or block

![Screenshot from 2021-07-04 16-47-09](https://user-images.githubusercontent.com/19241160/124387543-bf4d4380-dce7-11eb-947d-029cd5a2497f.png)

2021-07-04 14:48 UTC, jules-js commented on app/index.html
> +                    <figure class="articles__content flex_basis-25">
why it is as figure? this is article

2021-07-04 14:48 UTC, jules-js commented on app/index.html
> +                <div>
for what this div? remove it

2021-07-04 14:48 UTC, jules-js commented on app/scss/base/_base.scss
> +.menu {
move to modules

2021-07-04 14:48 UTC, jules-js commented on app/index.html
> +                    </div>
![Screenshot from 2021-07-04 16-51-46](https://user-images.githubusercontent.com/19241160/124387676-266af800-dce8-11eb-8d1d-55edf9695788.png)

very little space

2021-07-04 14:48 UTC, jules-js commented on app/scss/pages/home/_products.scss
> +        margin: 10px 15px;;
add covering column div with paddings
product shouldn't respond for layout

2021-07-04 14:48 UTC, jules-js commented on app/index.html
> +                    How it works
![Screenshot from 2021-07-04 16-54-24](https://user-images.githubusercontent.com/19241160/124387790-86619e80-dce8-11eb-9711-4005de31ec69.png)

2021-07-04 14:48 UTC, jules-js commented on app/scss/pages/shop/_shop_content.scss
> +    &__item {
fix the layout here according to the last lesson

2021-07-04 14:48 UTC, jules-js commented on app/scss/pages/shop/_shop_content.scss
> +        max-height: 354px;
fixed width and height, not max

2021-07-04 14:48 UTC, jules-js commented on app/shop.html
> +            <aside class="aside flex_basis-20">
**aside should be outer of the main tag**

2021-07-04 14:48 UTC, jules-js commented on app/shop.html
> +                        <div class="product__content">
recheck styles here, looks bad

2021-07-04 14:48 UTC, JuliaSavych commented on app/shop.html
> +                            <li class="shop__pages-item"><a class="shop__pages-link shop__pages-btn" href="#">Next</a>
semanticaly bad
this is a button out of ul

2021-07-04 14:48 UTC, JuliaSavych commented on app/shop.html
> +
remove empty lines

2021-07-04 14:48 UTC, JuliaSavych commented on app/shop.html
> +                    <nav class="menu">
better to name it "navigation"

2021-07-04 14:48 UTC, JuliaSavych commented on app/index.html
> +                <div class="comment__content flex_basis-50 flex_center flex_self-center text-center">
no .flex class
it doesn't work without a block!

2021-07-04 14:48 UTC, JuliaSavych commented on app/index.html
> +                            <p class="product__text articles__inner-text">
for what p??

2021-07-04 14:48 UTC, JuliaSavych commented on app/shop.html
> +                        <textarea class="aside__search-text" type="text" placeholder="Search by name..."></textarea>
this is input, not textarea

2021-07-04 14:48 UTC, JuliaSavych commented on app/shop.html
> +                <div class="shop__pages">
.pagination

2021-07-04 14:48 UTC, JuliaSavych commented on app/login.html
> +        <div class="modal container">
this is not a modal

2021-07-04 14:48 UTC, JuliaSavych commented on app/login.html
> +                            <form class="flex flex_center" action="#" method="get">
method="POST"

2021-07-04 14:48 UTC, JuliaSavych commented on app/login.html
> +    <footer class="footer">
footer should be fixed to the bottom of the page

2021-07-04 14:48 UTC, JuliaSavych commented on app/login.html
> +                                    <div class="form__controls form__controls_checkbox">
![Screenshot from 2021-07-04 17-05-56](https://user-images.githubusercontent.com/19241160/124388130-1fdd8000-dcea-11eb-9a28-31292861b07f.png)

elements are not aligned

2021-07-04 14:48 UTC, JuliaSavych commented on app/register.html
> +                                                name="confirm_password">
confirm_password - no such input type

2021-07-04 14:48 UTC, JuliaSavych commented on app/register.html
> +                                        <div class="form__login-title form__gender"><input class="form__gender_radio"
mising label

2021-07-04 14:48 UTC, JuliaSavych commented on app/register.html
> +                                            <p class="form__login-title">Last Name</p>
label

2021-07-04 14:48 UTC, JuliaSavych commented on app/register.html
> +                        <div class="tabs__content" id="register">
add wrapper to this content not to separate element

2021-07-04 14:48 UTC, JuliaSavych commented on app/login.html
> +<!DOCTYPE html>
fix mobile please
![Screenshot from 2021-07-04 17-39-42](https://user-images.githubusercontent.com/19241160/124389222-e22f2600-dcee-11eb-9db0-2803c18dc3cb.png)

2021-07-04 14:48 UTC, JuliaSavych commented on app/login.html
> +                <div>
for what this div?

2021-07-04 14:48 UTC, JuliaSavych commented on app/login.html
> +                <div class="header__buttons">
auth block

2021-07-04 14:48 UTC, JuliaSavych commented on app/register.html
> +<!DOCTYPE html>
![Screenshot from 2021-07-04 17-42-01](https://user-images.githubusercontent.com/19241160/124389317-35a17400-dcef-11eb-9899-e1557b0ccea2.png)
інпути мають марджин зліва - це не ок
вони мають бути строго вирівняні з лейблом

2021-07-04 14:48 UTC, JuliaSavych commented on app/scss/pages/shop/_aside.scss
> +    // top: 0;
remove commented code

2021-07-04 14:48 UTC, JuliaSavych commented on app/shop.html
> +<!DOCTYPE html>
1200px
![Screenshot from 2021-07-04 17-44-54](https://user-images.githubusercontent.com/19241160/124389405-9630b100-dcef-11eb-8ccd-48c90d5d2f9e.png)

2021-07-04 14:48 UTC, JuliaSavych commented on app/login.html
> +    <header class="header">
I don't like the way elements are horizontally aligned 
fix it please
![Screenshot from 2021-07-04 17-46-22](https://user-images.githubusercontent.com/19241160/124389458-d728c580-dcef-11eb-8aff-9c0627c971eb.png)

2021-07-04 14:48 UTC, JuliaSavych commented on app/login.html
> +    <header class="header">
they should be on the same baseline

2021-07-05 12:42 UTC, Roman240594 commented on app/shop.html
> +<!DOCTYPE html>
Не зрозумів, що тут потрібно пофіксити

2021-07-09 07:21 UTC, Roman240594 commented on app/index.html
> +                    <div class="banner__content-img position_relative">
Якщо встановити на background, тоді замовник не зможе змінювати цю картинку. А вона знаходиться на головній сторінці і ще й з самого верху. Хіба не доцільніше позиціонувати її?

2021-07-09 08:40 UTC, Roman240594 commented on app/shop.html
> +                        <div class="product__content">
Класи перевикористовую з першої сторінки. Тому назви не такі як у цій батькійському елементі. Створити нові класи і продублювати майже всі стилі?

2021-10-11 12:16 UTC, merged